database:
    driverClass: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:mymemdb
    validationQuery: "SELECT * FROM INFORMATION_SCHEMA.SYSTEM_TABLES"

    properties:
        hibernate.dialect: org.hibernate.dialect.HSQLDialect
        hibernate.hbm2ddl.auto: create

server:
    type: simple
    rootPath: /api/*
    applicationContextPath: /

logging:
    level: OFF